# Generated by Django 3.2.8 on 2021-10-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advisor_name', models.CharField(max_length=50)),
                ('advisor_img_url', models.CharField(max_length=5000)),
            ],
        ),
    ]
