# Generated by Django 3.2.8 on 2021-10-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nltask_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
