# Generated by Django 3.2.8 on 2021-10-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nltask_app', '0002_user_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_login',
        ),
        migrations.AlterField(
            model_name='advisor',
            name='advisor_img_url',
            field=models.URLField(max_length=5000),
        ),
    ]
